version: '3.4'

services:
  mymonolithicapp.host:
    image: ${DOCKER_REGISTRY-}mymonolithicapphost
    build:
      context: .
      dockerfile: src/MyMonolithicApp.Host/Dockerfile
    depends_on:
      - mymonolithicapp.database
  mymonolithicapp.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - "MSSQL_PID=Express"
      - "SA_PASSWORD=Abcd*1234"
      - "ACCEPT_EULA=Y"
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume: {}